import { useState } from "react"
import Store from "./ContextApi"

const ContextApi = (props) => {

    const [data,setdata] = useState([
    {
        id:1,
        cat:"Bollywood-Images",

        img1:"https://images-na.ssl-images-amazon.com/images/S/pv-target-images/59051f54c9d4f3a050555322a424b2af4df3559a76bda6d99c42478a482806b6._RI_TTW_.jpg",
         title1:"Dhamaal",
        info1:"DHAMAAL lives up to its title. It's non-stop dhamaal for the next two hours. Sure, there're inane situations and jokes that cater to the popular tastes, but when did Indra Kumar and his team of writers [Paritosh Painter, Balwinder Suri, Bunty Rathore] ever set out to challenge Einstein? The mantra is simple: Let the auditorium reverberate with laughter. And DHAMAAL succeeds in its mission!",
        apara1:"Any hiccups? The post-interval portions aren't as funny as the first hour. More on that later! But the film works in totality and that's what matters at the end of the day. With MASTI, Indra Kumar proved that he knows how to tickle the funny bone. With PYARE MOHAN, he tripped and ended up bruising himself. With DHAMAAL, he sprints back to the junta's hearts.",
         apara2:"Roy [Riteish Deshmukh] believes that he is the best detective in the world. Manav [Javed Jaffrey] actually happens to be the biggest idiot in the world, but is blissfully unaware about it. His brother Adi's [Arshad Warsi] half knowledge about everything only adds to the great expertise of this group. The final component is Boman [Aashish Chowdhary], who's Mr. Scared.",
         apara3:"The one performance that stands out from the rest is that of Javed Jaffrey's. He's magnificent in a role that seems tailor-made for him. What timing! The viewers are sure to go into raptures. Arshad Warsi is not in his element. Also, why is he looking so tired? Ritesh Deshmukh is dependable yet again, although his track suffers in the second hour because it lacks meat. Aashish Chowdhary is a revelation. Confident and easygoing, he shows a flair for comedy. Sanjay Dutt is alright. Asrani is mind-blowing. It's a treat to watch this veteran in a meaty role again. Suhasini Mulay, as the landlady, is first-rate.",

        img2:"https://www.hollywoodreporter.com/wp-content/uploads/2015/07/bahubali_warrior_poster_p_15.jpg?w=2000&h=1126&crop=1",
        title2:"Bahubali : The Conclusion",
        info2:"Fans of the Baahubali franchise have been discussing the hashtag on the social media for a while now. If you have not guessed yet, that stands for “Why Kattappa Killed Baahubali”, a reference to the teaser in the closing scene of Baahubali: The Beginning in 2015. You will not find spoilers on the front in this review.",
        bpara1:"In the first film, the tribal boy Shivudu (Prabhas) discovered that he is, in fact, Mahendra Baahubali, son of the late great Amarendra Baahubali (also Prabhas) who was robbed of the throne of Mahishmati kingdom by the machinations of his cruel cousin Bhallaladeva (Rana Daggubati) and uncle Bijjaladeva (Nassar). In Baahubali: The Conclusion, Mahendra hears the story of why and how that happened before setting off to avenge the deaths of his father and foster grandmother Sivagami (Ramya Krishna) and to free his mother Devasena (Anushka Shetty) from imprisonment in Mahishmati.",
        bpara2:"Declaring Amarendra Baahubali King does not ease the tension between the two step-brothers and rivals as Bhallaladeva considers himself the rightful King, being the biological son of the Mother Queen. As we found out in the previous movie, Amarendra Bahubali is the son of the old King, and his mother died giving birth to him. The Kings brother was seen as too weak and cowardly to take over the throne, so his wife Sivagami, sister-in-law of the King had the conspirators to the throne killed and assumed the throne herself. She was to hold power until one of the two princes proved he was capable enough of taking over the responsibility of the throne.",
        bpara3:"Since Amarendra Baahubali was to take over the throne, Sivagami orders him to travel throughout the kingdom and surrounding areas and become familiar with the people and various smaller kingdoms that existed within the land so that he understood the land and the state of the people he would be ruling over. She also sends Katappa (Sathyaraj) along with him as a companion and bodyguard. In the meanwhile, the Sivagami would prepare for his coronation and search for a suitable bride.",

        img3:"https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/K.G.F_Chapter_2.jpg/220px-K.G.F_Chapter_2.jpg",
        title3:"K.G.F: Chapter 2",
        info3:"One of the highest collection movies in India, K.G.F.: Chapter 2 was released in 2022 and is the sequel to K.G.F. that came out back in 2018. The two-part series follows and narrates the life of renown assassin Rocky,...",
        cpara1:"KGF:Chapter 1' set the tone for a slick gangster franchise-high on style and details. The first part was all about establishing the intentions and power of Raja Krishnappa Bairya aka Rocky Bhai. The second part has managed to create hype with its promotional content that gives a peek into the film. Does the film manage to match the build-up? It does and provides a better sequel and also has a big surprise for fans in the end, too.",
        cpara2:"The film begins with Vijayendra Ingalagi, the son of Anand Ingalagi, taking over as the narrator. Rocky has won over the people of KGF and he is now in the process of dreaming bigger and treading more dangerous paths. In this process, he encounters Adheera, who is inspired by the Vikings and evokes visceral fear, who wants KGF back. Simultaneously, he also has to encounter the righteous Prime Minister Ramika Sen, who also wants Rocky taken down.",
        cpara3:"The story progresses at a brisk pace in a racy tale of Rocky's journey to the top. The film, like the first part, presents a dark, dreary world that is stylishly shot. While the first part took time to prove who the protagonist was and included more time to establish the same, this second part moves quicker and one gets to meet more characters. The conflicts and battles are more interesting this time.",

        img4:"https://www.koimoi.com/wp-content/new-galleries/2021/12/ram-charan-gives-rrr-trailer-launch-a-miss-001.jpg",
        title4:"RRR",
        info4:"S.S. Rajamouli does it again with RRR, a 2022 film that attained a massive fan following and traction among cinema enthusiasts. The action drama is one of South India’s best marvels...",
        dpara1:"The Telugu language Indian action epic “RRR” (short for “Rise Roar Revolt”) has returned to US theaters for an exceptional one-night-only engagement on June 1st following its initial theatrical release. Some hindsight has made it easy to guess why writer/director S.S. Rajamouli has only now broken through to Western audiences with “RRR” despite his consistent box office success. Rajamouli’s latest is an anti-colonial fable and buddy drama about the imaginary combo of two real-life freedom fighters, Komaram Bheem (N.T. Rama Rao Jr.) and Alluri Sitarama Raju (Ram Charan). “RRR” is also a fine showcase for Rajamouli’s characteristic focus on maximalist action choreography, overwhelming stuntwork and pyrotechnics, and sophisticated computer graphics.  ",
        dpara2:"By the time he made “RRR,” Rajamouli had already developed his brand of Nationalistic self-mythologizing with some help from recurring collaborators like regular story writer (and biological father) Vijayendra Prasad and both co-leads, who previously starred in Rajamouli’s “Yamadonga” and “Magadheera,” respectively.",
        dpara3:"Set in and around Delhi in 1920, “RRR” pointedly lacks historical context so that Rajamouli and his team can transform a straight-forward rescue mission into a rallying cry for reunification and also cathartic violence. Bheem, the avenging “shepherd” of the Adivasian Gond tribe, visits Delhi to track down Malli (Twinkle Sharma), an innocent pre-teen who’s kidnapped from her Gondian mother by the cartoonishly evil British Governor Scott (Ray Stevenson) and his sadistic wife Cathy (Alison Doody).",

        img5:"https://upload.wikimedia.org/wikipedia/en/5/50/Secret_Superstar_-_Poster_3.jpg",
        title5:" Secret Superstar",
        info5:"Musical dramas are usually responsible for attracting huge crowds, and that was also the case with Secret Superstar starring Aamir Khan. It has the highest box office collection in india to its credit. ",
        epara1:"Insia Malik (Zaira) is a talented 15-year-old school girl from Baroda whose spirit is ripped because her mother is in a troubled and violent marriage. Of course she still dares to pursue her dream of becoming a singer and she also valiantly attempts to free her mother from her conservative, cold father.When Aamir Khan backs a film, you expect quality. The actor who plays an obnoxious music director, Shakti Kumaarr, in this outing, doesn’t let you down on that count.",
        epara2:"Nothing is new here. Whether it is batting for the girl child or freeing a battered housewife from the shackles of a loveless marriage, the material at hand has been touched on earlier. But what makes 'Secret Superstar' stand out is the adventurous narrative that keeps you rooted and guessing. You can feel the frustration of the Malik household in which not just people, even emotions are trapped. When the protagonist breaks free, you find yourself simultaneously wiping your tears and doing a victory lap.",
        epara3:"Aamir is the scene-stealer. His character — a cross between the brash American Idol judge Simon Cowell and your crass Bollywood music directors from the 80-90s — appears like a caricature at the start. But you invest in him eventually because of the nuances he brings. It is also commendable that he never really attempts to steal the limelight from young Zaira, who is an absolute delight to watch. Najma (Meher) as the submissive wife says so much without spelling it out. And others like — Chintan (Tirth Sharma) and child-actor Guddu (Kabir) are adorable.",

        img6:"https://images-na.ssl-images-amazon.com/images/S/pv-target-images/59051f54c9d4f3a050555322a424b2af4df3559a76bda6d99c42478a482806b6._RI_TTW_.jpg",
        title6:"Dhamaal",
        info6:"DHAMAAL lives up to its title. It's non-stop dhamaal for the next two hours. Sure, there're inane situations and jokes that cater to the popular tastes, but when did Indra Kumar and his team of writers [Paritosh Painter, Balwinder Suri, Bunty Rathore] ever set out to challenge Einstein? The mantra is simple: Let the auditorium reverberate with laughter. And DHAMAAL succeeds in its mission!",
        fpara1:"Any hiccups? The post-interval portions aren't as funny as the first hour. More on that later! But the film works in totality and that's what matters at the end of the day. With MASTI, Indra Kumar proved that he knows how to tickle the funny bone. With PYARE MOHAN, he tripped and ended up bruising himself. With DHAMAAL, he sprints back to the junta's hearts.",
        fpara2:"Roy [Riteish Deshmukh] believes that he is the best detective in the world. Manav [Javed Jaffrey] actually happens to be the biggest idiot in the world, but is blissfully unaware about it. His brother Adi's [Arshad Warsi] half knowledge about everything only adds to the great expertise of this group. The final component is Boman [Aashish Chowdhary], who's Mr. Scared.",
        fpara3:"The one performance that stands out from the rest is that of Javed Jaffrey's. He's magnificent in a role that seems tailor-made for him. What timing! The viewers are sure to go into raptures. Arshad Warsi is not in his element. Also, why is he looking so tired? Ritesh Deshmukh is dependable yet again, although his track suffers in the second hour because it lacks meat. Aashish Chowdhary is a revelation. Confident and easygoing, he shows a flair for comedy. Sanjay Dutt is alright. Asrani is mind-blowing. It's a treat to watch this veteran in a meaty role again. Suhasini Mulay, as the landlady, is first-rate.",
   

        img7:"https://static.toiimg.com/thumb/msid-61259441,width-219,height-317,imgsize-147055/61259441.jpg",
        title7:"ROBOT",
        info7:" Dr Vasi (Rajnikanth) is a scientist with a mission. He wants to create the first robot which would not only serve tea and coffee to its masters but would have the power to serve humanity in more meaningful ways.Can the creator tame the rogue robot or will machine rule over man.",
        gpara1:"He creates Chitti, the humanoid who looks like him and is willing to do anything for him. Trouble begins when he goes a step further and teaches the machine to feel. Chitti falls in love with the professor's girl friend, Sana (Aishwarya Rai) and ends up becoming an almost undefeatable rival in love, courtesy the red chip that a rival scientist (Danny Denzongpa) infuses in him. Can the creator tame the rogue robot or will machine rule over man?",
        gpara2:"The film begins with an old man committing suicide from atop a mobile phone tower. We are then introduced to scientist, Dr Vasigaran (Rajinikanth) and his now assistant Nila (Amy Jackson), a humanoid robot. Soon, mobile phones start flying off the shelves and out of everyone's hands, and Vasigaran is called in to investigate this mysterious occurrence. And when a giant bird, made up of mobile phones, starts attacking the city, the scientist is forced to bring back Chitti (Rajinikanth), the now dismantled robot.",
        gpara3:"Want to see what mainstream Indian cinema actually means? Go, watch Robot. The last 30 minutes of the film are literally the baap (grandmaster) of all make-believe and end up creating a whole new genre of cinema: the 'curry eastern' which stands up as a wholesome alternative to the curry western. For Rajnikanth fans, the climax is definitely a sure-fire way to lose your sanity.",
                                  // Top Post

        img8:"https://venkatarangan.com/blog/wp-content/uploads/2023/02/2023-pathaan-movie-poster.jpg",
        title8:"Pathaan !!!Once again, a action role of the list of highest grossing movies...",
        hpara1:" With a star-studded casting, Pathaan brings back the hit combo of Shah Rukh Khan & Deepika Padukone. This will be their fourth movie together after giving hits like Om Shanti Om, Chennai Express, and Happy New Year. Shah Rukh will be playing the role of a RAW field agent.",
        hpara2:"Pathaan also brings back John Abraham & Deepika after a long wait of 10 years. Fans loved them as love birds in Desi Boyz & as Siblings in Race 2. If you loved seeing John in negative roles — Pathaan is going to be exciting. Yup! He is the main antagonist in the movie.",
        hpara3:"After 4 years of exile, SRK is back to rule the box office with Pathaan. The movie is set to release on the 25th of January, 2023 — strategically planned for the Indian Republic day weekend. If you’ve been missing the SRK magic of Main Hoon Na, Don, and Jab Tak Hain Jaan, Pathaan might end it. ",

        img9:"https://m.media-amazon.com/images/M/MV5BNjc5MTAwZjAtYWMxNy00YzdhLWE5NzItMDA3MzFmZDRkYzFmXkEyXkFqcGdeQXVyNzc4NzEwNTc@._V1_.jpg",
        title9:"Sanju",
        ipara1:"Sanju explores some of the most crucial chapters from movie star Sanjay Dutt’s dramatic and controversial real life. It gives a lowdown on his tryst with drugs and his trials and tribulations in the Arms Acts case and the 1993 Mumbai blasts.",
        ipara2:"One man, many lives is just the tip of the iceberg when it comes to Sanjay Dutt. Rajkumar Hirani’s film presents a vivid and very dramatic look in this biopic of sorts. The film starts off with Sanjay Dutt (Ranbir Kapoor) wanting a writer for his biography even while he's preparing to surrender himself to the Supreme Court's judgement in the Arms Act case. A film writer fails him miserably, so Sanju turns to a more established writer Winnie (Anushka Sharma) to pen his biography. His confessions and recollections to Winnie are intimate and give us deep insights into the highs and lows of his life, which is nothing short of a roller-coaster ride. Like any Rajkumar Hirani film, Sanju blends humour with drama effortlessly.",
        ipara3:"While it doesn't reveal much about the protagonists’ relationships and marriages, it does tell a strong story of an unbreakable bond between a father, son and a best friend. In fact, Sanjay’s relationship with his father Sunil Dutt (Paresh Rawal) forms the major part of this story and some of the most heart wrenching and touching moments in the film belong to both of them.",

        img10:"https://images.bewakoof.com/image/content/2022/12/01184459/image-14.png",
        title10:"War",
        info10:"Indian cinema-goers seem to be obsessed with secret-agent",
        jpara1:"Two stars and firm favourites of the action genre, Hrithik Roshan and Tiger Shroff, lock horns in War. It’s a juicy proposition for fanboys and girls of both actors. A sort of millennial throwback to the 90s showdown between Sanjay Dutt and Jackie Shroff in Subhash Ghai's Khalnayak. But apart from this talking-point premise, War, serves up a lot more for the action-movie buffs. It has lots of stunts, thrills, twists and just enough masala and explosions to keep you engaged in the first half, but once the big reveals happen in the second half of the story, it goes awry. Where the film excels in action set pieces, it genuinely falls short on the story front.",
        jpara2:"But the story is in all fairness, secondary to the idea of watching two handsome hunks squaring off in a duel of high-octane stunts (action directors — SeaYoung Oh, Parvez Shaikh, Franz Spilhaus and Paul Jennings). It’s like the two heroes, Hrithik and Tiger, known for their bulging muscles and crisp six-pack abs are out to beat each other in a competition of pure brawn. Kabir and Khalid, punch, kick and pound each other to a pulp, and watching the two actors put on a show of their chiselled good looks is a sight for the fans. Hrithik Roshan is in top form as the anti-hero and Tiger matches up to his senior in both smouldering on-screen intensity and the high-flying action.",
        jpara3:"Both actors feed off each other’s ability to ace good-looking action. And when they’re not fighting for supremacy, they’re trying to out-dance each other in foot-tapping numbers. Vaani Kapoor has a small role, where she mostly manages to up the glamour quotient of the movie. Ashutosh Rana brings his usual dialled-up intensity to his performance, as well.Like the quintessential entertainer, War serves up a little bit of everything in its narrative — action, drama, music, romance, exotic locations and car chases. The screenplay makes room for every commercial movie element. In a bid to make it Hollywood-esque, director Siddharth Anand and his team have designed the many stunts of the film to recreate thrills that you’d usually watch in movies like Mission Impossible and Fast And Furious. ",

        img11:"https://www.filmibeat.com/ph-big/2019/09/saaho_156836864110.jpg",
        title11:" Saaho",
        kpara1:"Billed as India's biggest action entertainer, Saaho is all about the feud among a few members of world's biggest crime syndicate, based out of Waaji city, somewhere away from India. Some of the over ambitious and brutal men (and a woman) of the gang finish off Roy (Jackie Shroff), their leader, in order to obtain a secret black box through which they aspire to become billionaires.",
        kpara2:"Meanwhile, cops in India are after a smart thief (Neil Nitin Mukesh) who looted two lakh crore rupees. The team is headed by Ashok (Prabhas) and Amrita (Shraddha Kapoor). After thorough investigation, it's revealed that there's a link between the huge sum and Waaji city. The arrival of Vishwa (Arun Vijay), the son of Roy, makes the plot more intriguing as he sets out to find his father's murderer and the lost money in India.",
        kpara3:"A movie made on such a grand scale with numerous actors needs a gripping screenplay and convincing characterisations, and that's exactly what Saaho lacks. There is a hero and the mandatory heroine, and there are way too many villains that it becomes difficult to focus on these many character on screen. None of the antagonists leave a big impact, and this results in a lack of emotional connect with the protagonist.",
    },
    {  
        id:2, 
        cat:"Technology-Images",

        img1 :"https://techcrunch.com/wp-content/uploads/2023/05/GettyImages-1360703491.jpg?w=430&h=230&crop=1",
        title1:"Improving Developer Experience is now a priority",
        info1:"Internal developer portals have emerged as a one-stop shop that lets developers in an organization access all the microservices and tools available to them.",
        apara1:"Internal developer portals are a welcome tool to alleviate the cognitive load of developers, and could go one step further as they start incorporating AI. But it’s not just developers who could benefit from AI soon — so could nurses, thanks to a new startup supported by the Allen Institute’s AI2 Incubator. — Anna",
        apara2:"Internal developer portals have emerged as a one-stop shop that lets developers in an organization access all the microservices and tools available to them. But they are not just service catalogs: They also enable companies to build self-serve actions that developers can perform.",
        apara3:"The wider adoption of internal developer portals is correlated to another trend: the rise of platform engineering teams, whose role is to empower other developers. Both of these concepts have become central to improving the developer experience, a priority for many organizations.Organizations aren’t moved purely by the goodness of their hearts. After all, cognitive overload isn’t exactly new for developers, even if SaaS sprawl and the rise of microservices have arguably made it worse.",

        img2:"https://techcrunch.com/wp-content/uploads/2023/05/GettyImages-1360703492.jpg?w=430&h=230&crop=1",
        title2:"Deal Dive:Gradiant is the new kind of unicorn worth getting excited about",
        info2:"The 10-year old company that’s been grinding away in a tough industry offers a lot of hints of what the unicorns of 2023 will look like.",
        bpara1:"A company reaching the billion-dollar valuation mark used to be a rare event — hence the term “unicorn.” But by 2020 and 2021, it was anything but. Every week was like, “Oh, another crypto unicorn? Great. Wow, the fifth neobank this month. Amazing. Wait, wasn’t that company just founded last year?”",
        bpara2:"I’m not saying this to diminish the accomplishments of any of those companies, but the investing fever of 2020 and 2021 made that once-scarce milestone almost seem like late-stage table stakes.But in today’s tougher funding market, unicorns are rare again. And there is a new entrant that shows us what unicorns might look like in 2023.",
        bpara3:"This week, Boston-based Gradiant said it raised a $225 million Series D round led by Centaurus Capital at a $1 billion valuation. The company builds tools to manage and treat wastewater for companies across industries such as food and beverage, pharmaceuticals and mining.Gradiant’s co-founder and CEO, Anurag Bajpayee, told TechCrunch+ that the company has essentially doubled revenue every year, for the last few years.",

        img3:"https://techcrunch.com/wp-content/uploads/2023/05/coinbaseone_emailhero_720x400px.png?w=430&h=230&crop=1",
        title3:"Coinbase launches subscription service with focus on european expansion ",
        info3:"Coinbase is launching its subscription service, Coinbase One, in 35 countries, starting with U.S., U.K., Germany and Ireland",
        cpara1:"Coinbase, the world’s second-largest crypto exchange, is launching its subscription service, Coinbase One, in 35 countries in a bid to retain users and grow its recurring revenue streams as the crypto economy struggles through a bearish market.Coinbase One was originally introduced in fall 2021 in beta and will be available publicly today onward in the U.S., United Kingdom, Germany and Ireland, the company exclusively told TechCrunch+.",
        cpara2:"The company will roll the service out in 31 other European countries in the coming months.The subscription service offers a host of features, including no trading charges, higher staking rewards, 24/7 customer support and pre-filed tax return documents, according to Phil McDonnell, senior director of product management at Coinbase.",
        cpara3:"In the past, a lot of Coinbase’s revenue came from trading fees, especially during the bull market, but as the crypto winter drags on, the company is looking to other areas to drive growth and diversify its revenue streams.“Maybe 18 months ago, it was very transactional,” McDonnell said. “People come in, trade, pay a fee, and that was the relationship. Through the bull market 18 months to two years ago, there was tons of growth, but we wanted customers to stay […] That was the inspiration. How do we build a longer, deeper relationship with our customers and make it a win-win?”",

        img4:"https://techcrunch.com/wp-content/uploads/2023/05/GettyImages-1461608537.jpg?w=430&h=230&crop=1",
        title4:"Retail media targeting on the AI maturity curve",
        info4:"Let’s look at the three most important milestones along the road to predictive analysis in the retail media context",
        dpara1:"This is a simplified view of how a retailer’s data and AI capabilities (charted on the x-axis) directly correlate with the competitive advantage of its retail media network (charted on the y-axis). A general strategic approach following this curve will see retailers making incremental steps toward sophistication, inching ever closer to the vaunted “predictive analysis” that will allow them to anticipate customer needs and deliver finely tuned, personalized experiences.",
        dpara2:"The “on-ramp” to this curve for any retailer looking to harness the power of data and AI begins with a full view of clean and accepted data across all customer interactions and media placements, whether physical or digital, owned or rented. This data is crucial for understanding the opportunity, managing yield and accurately measuring campaign performance.",
        dpara3:"As technology formalizes retail media as a category, the chance to lead on metric integrity and data quality is significant. Understanding the unique count of customers along the journey through physical and digital touch points is also crucial, as duplicating customer counts to inflate the value of the media network is a risk to both trust and budget growth in the long term.",

        img5:"https://techcrunch.com/wp-content/uploads/2023/05/GettyImages-680216789.jpg?w=430&h=230&crop=1",
        title5:"Here’s what I learned while leading a bootstrapped startup to $40M ARR",
        info5:"Since our founding in 2014, we’ve reached $40 million in ARR through bootstrapping. From there, it was off to the races.",
        epara1:"Building a business from the ground up comes with its fair share of learning experiences and missteps. But, one of the greatest challenges we were able to avoid was starting with a finished product. We decided before even coming up with a name, that the most important thing would be to start with a minimum viable product (MVP). In other words, the bare minimum required for someone to use it and get value out of it.",
        epara2:"From previous projects, the team knew that waiting to finish the product and then releasing it would invite challenges. Had the team waited to finish the product and then attempt to collect feedback, we would have risked spending a long time moving in the completely wrong direction. Creating our MVP allowed us the flexibility to build and release as we learned, and it proved successful.",
        epara3:"Since our founding in 2014, we’ve reached $40 million in ARR through bootstrapping. From there, it was off to the races. We continued to see exponential product-led growth (PLG): When we officially launched, we had 27,562 users (including customers), and we were growing at a steady 10% per month with a PLG strategy.",

        img6:"https://techcrunch.com/wp-content/uploads/2023/05/IMG_5632.jpeg?w=430&h=230&crop=1",
        title6:"Self-driving cars are taking ages to become a reality, but they won’t take forever",
        info6:"My dream of never having to drive again is far from dead. I just need to add five or 10 years to my prior timelines.",
        fpara1:"There’s a lot of good news to be found. Today, Chinese technology giant Baidu revealed an interesting set of data points regarding Apollo Go, it’s “autonomous ride-hailing service”:Apollo Go, Baidu’s autonomous ride-hailing service, provided around 660K rides in the first quarter of 2023, up 236% year over year and 18% quarter over quarter.",
        fpara2:"The company also reminded investors that Apollo Go was the first to receive permits in Beijing to “operate ride-hailing services with no driver or safety operator in the vehicles” this March.So if we presume an average trip of, say, two miles (3.2 kilometers), Apollo Go racked up north of one million miles in the first quarter alone.",
        fpara3:"That’s a lot of autonomous driving.Baidu’s update follows other progress reports from self-driving car outfits: Cruise a couple of months ago said it had completed “one million fully driverless miles” in the 15 months since it started offering fully driverless rides.We also covered Cruise’s geographic expansion earlier in May:Cruise is rolling out its self-driving cars to more cities — specifically, to Houston and Dallas as it expands its Texas-based presence. Cruise already started testing its vehicles in Austin at the end of last year, and announced plans to begin testing its Origin built-for-purpose robotaxis there earlier in 2023.",

        img7:"https://techcrunch.com/wp-content/uploads/2019/02/ai-assisted-translation.png?w=430&h=230&crop=1",
        title7:"As AI consumes search, what will be left for us humans?",
        info7:"I hope that you’ll still want to read my stuff in the future. If not, at least I probably helped train my replacement.",
        gpara1:"As with all major evolutions in technology, these changes to search will have broad and lasting impacts. There will be winners and losers, and among the latter, at least according to early reviews of Google’s new changes to search, will be websites that host writing.",
        gpara2:"Google and Bing will quickly grow adept at using large language models to generate answers to questions, precluding the need to visit websites to find answers. As a result, media companies, bloggers and scrappy SaaS startups could see fewer visits to their websites and less attention paid to their offerings.",
        gpara3:"Until the generative AI rush, changes to search engine tech felt incremental, unless it was for monetizing user activity. Google has toiled for years to increase the amount of answers users get on its search pages so they don’t head elsewhere and has sometimes smoothed its advertising load so search results highlight its customers more than websites that don’t advertise.",
                                                  // Top Post 

        img8:"https://techcrunch.com/wp-content/uploads/2022/05/GettyImages-1338889969.jpg?w=430&h=230&crop=1",
        title8:"Tensor is climbing to the top of the Solana NFT marketplace totem pole",
        info8:"Just two months ago, Tensor raised $3 million in a seed round. Fast forward to today, and it is close to regaining its position as the biggest Solana-based NFT marketplace based on market share. ...",
        hpara1:"Just two months ago, NFT trading platform Tensor raised $3 million in a seed round. Fast forward to today, and it is close to regaining its position as the biggest Solana-based NFT marketplace based on market share.“A lot of momentum came from the announcement,” Tensor co-founder Richard Wu said, speaking about the seed round, which TechCrunch covered exclusively in March. “When it comes to a marketplace, liquidity is key to attract users, and it had a snowball effect on itself.”",
        hpara2:"“A lot of momentum came from the announcement,” Tensor co-founder Richard Wu said, speaking about the seed round, which TechCrunch covered exclusively in March. “When it comes to a marketplace, liquidity is key to attract users, and it had a snowball effect on itself.”Tensor last week reached 45% of Solana’s NFT market share, surpassing Solana-centric NFT marketplace Magic Eden’s 44% share over a seven-day period, according to data collected by Tiexo.",
        hpara3:"While the 1% difference may seem nominal, it’s a huge jump for a fairly new platform up against a giant with almost 200x the users.Tensor launched a private beta in June 2022 and opened to the public the following month. In March, it had over 30,000 monthly active users, and by April, its MAU was up about 317% to over 125,000, co-founder Ilja Moisejevs said.Compared to Magic Eden, which has 22 million unique monthly visitors, that makes its share of the market is substantial.",

        img9:"https://techcrunch.com/wp-content/uploads/2019/03/GettyImages-974037824.jpg?w=430&h=230&crop=1",
        title9:"Yeah, tech growth is slowing down",
        ipara1:"The answer seems to be their growth forecasts for the year, which came in below what Wall Street was hoping for.While we were less than impressed with how slowly the largest American tech companies are expanding their revenue, it appears we’re not dealing with an issue that only impacts Big Tech. Their smaller peers are seeing similar headwinds, too.",
        ipara2:"This morning, we’ll go over each company’s results and then we’ll hear from Amplitude CEO Spenser Skates. Lastly, we’ll look at a broader index of modern software companies’ growth rates and put all that together to glean takeaways for startups.The (financial) road ahead",
        ipara3:"Airbnb needs no introduction, so we can jump straight to the numbers. The company reported better-than-expected revenue and its first GAAP profit in the quarter, while also generating fistfuls of cash. It certainly feels like a good result, especially given that revenue expanded 20% at Airbnb’s age in this economy.However, Airbnb expects revenue to increase by 12% to 16% in the second quarter from a year earlier. That’s quite a bit less than the 58% growth it saw in Q2 2022, and it’s also a decline from the 20% it grew in Q1 2023.",
       

        img10:"https://techcrunch.com/wp-content/uploads/2023/05/GettyImages-1224612965.jpg?w=430&h=230&crop=1",
        title10:"Generative AI and copyright law: What’s the future for IP?",
        jpara1:"The guidance emphasizes the importance of human authorship and outlines how the office evaluates works containing AI-generated content to determine whether the AI contributions are the result of “mechanical reproduction” or an author’s “own original mental conception.”",
        jpara2:"The Copyright Office will not register works whose traditional elements of authorship are produced solely by a machine, such as when an AI technology receives a prompt from a human and generates complex written, visual or musical works in response. According to the Office, in these cases, the AI technology, rather than the human user, determines the expressive elements of the work, making the generated material ineligible for copyright protection.",
        jpara3:"However, a work containing AI-generated material may still be eligible for copyright protection if it also contains sufficient human authorship. Examples include a human selecting or arranging AI-generated content in a creative way or an artist modifying AI-generated material to the extent that the modifications meet the standard for copyright protection. In these cases, copyright protection only applies to the human-authored aspects of the work.",

        img11:"https://techcrunch.com/wp-content/uploads/2023/05/GettyImages-1373749318.jpg?w=430&h=230&crop=1",
        title11:"Western sanctions against Russia: Tips for tech companies managing compliance risk",
        kpara1:"The war in Ukraine rages on, authorities are cracking down on the smuggling of U.S. technology in support of Russia’s war effort, an initiative with implications for the tech industry. One significant example of this is Russia’s drone program, with a December 2022 expose describing U.S. chips, circuit boards, and amplifiers found in downed Russian drones, and mapping part of the supply chain trafficking such items to Russia in spite of Western sanctions.",
        kpara2:"This has prompted broader concerns regarding the diversion of Western technology to Russia in support of illicit end-uses, such as, for example, the Russian government’s use of facial recognition technology to crack down on dissidents.In response to this, the United States and its partners recently imposed new sanctions against Russia to coincide with the one-year anniversary of the invasion of Ukraine, including expanded export controls over drone components, electronics, industrial equipment, and other items.",
        kpara3:"The U.S. government followed this up with an advisory warning companies of the risk of third parties diverting their products to Russia.Suppliers of electronics, drone components, and other sanctioned items face the risk that third parties will divert their products to Russia’s defense industrial base or to the battlefield in Ukraine, given the Russian military’s continued demand for battlefield equipment. Companies can mitigate this risk by conducting due diligence on counterparties and by auditing sales channels.",
    },
    {
        id:3,
        cat:"Hollywood-Images",

        title1:"OPPENHEIMER OFFICIAL NEW TRAILER",
        img1:"https://i0.wp.com/jasonsmovieblog.com/wp-content/uploads/2023/05/maxresdefault-e1683589706478.jpg?resize=1200%2C390&ssl=1",
        info1:"Witness history in the making as Universal Pictures releases the new official trailer for director Christopher Nolan’s latest film Oppenheimer. View trailer below.",
        apara1:"Witness history in the making as Universal Pictures releases the new official trailer for director Christopher Nolan’s latest film Oppenheimer. View trailer below.The film follows the life of theoretical physicist J. Robert Oppenheimer, the director of the Los Alamos Laboratory during the Manhattan Project, and his contributions that led to the creation of the atomic bomb.",
        apara2:"Oh interesting. I wasn’t expecting a new trailer for this movie, but I do welcome it! As I’ve previously stated before, I’ve always been a fan of Nolan’s work, so to see this skilled director take such ambitious subject matter of covering the creation of the atomic bomb seems intriguing right from the get-go. This new trailer boasts plenty of new dramatic tension within the new footage as well as the sprawling recognizable cast. Overall, I’m very much excited to see Oppenheimer this summer.",
        apara3:"“I know of no more dramatic tale with higher stakes,” Nolan said, introducing the footage to the assembled film aficionados. Further to its varied aesthetic, Variety described the footage as “nail-biting,” with scenes of “the physicist's team engaged in the top-secret work of bomb-making,” also zipping forward chronologically to “a point where Russia has developed its atomic technology, triggering suspicions of espionage at Los Alamos.” Sounds like a good ol' fashioned political thriller, centred on a story with massive historical consequences.",

        title2:"CHEVALIER (2023) REVIEW",
        img2:"https://i0.wp.com/jasonsmovieblog.com/wp-content/uploads/2023/04/461294-e1682802993496.jpg?zoom=2&resize=860%2C280&ssl=1",
        info2:"CLASSICALLY BOLD   Over the years, the dramatic efforts of biopic endeavors have been something of a cinematic fascination with Hollywood, finding filmmaking talents both in front and behind the camera flocking to be a part of these theatrical motion pictures.",
        bpara1:"Over the years, the dramatic efforts of biopic endeavors have been something of a cinematic fascination with Hollywood, finding filmmaking talents both in front and behind the camera flocking to be a part of these theatrical motion pictures. While the idea of creating a biographical feature film about someone and / or some event isn’t anything new, it is something that’s quite beguiling of capturing the essence / mystique of a character who is based in real life and presenting he / she for a dramatic picture. Some of these endeavors might shed light on their entire life (providing the “life and times” of a particular person), while others might focus on a particular moment and / or a significant point of their lives. Recently, Hollywood has somewhat basked in the idea of creating biopic dramas; finding many talented actors / actresses getting their chance to shine and “dig deep” within their characters to create some powerful and sometimes high caliber performances of their careers as well as unearthing untold stories of several unsung heroes and / or pioneers of their era.",
        bpara2:"In truth, biopic dramas can pull from many stories of famous individuals from famous leaders (The Queen and Lincoln) to powerful figures of state (Darkest Hour and Vice), to real-life scenarios of unsung heroes (Sully and Patriots Day), to business moguls (Steve Jobs and The Founder), to musicians (Straight Outta Compton and Bohemian Rhapsody), and to literature minds (Finding Neverland and Goodbye Christopher Robin). Now, Searchlight Pictures (along with Element Pictures and TSG Entertainment) and director Stephen Williams present the latest film in the biographical cinematic realm with the release of Chevalier, a theatrical movie into the untold tale of talented virtuoso Joseph Bolgone. Does this film find an “instrumental” balance between cinematic presentation and historical truth or is it a mellow drama period piece that gets lost within its own narrative conventions?",
        bpara3:"Set during the pre-revolution days in Paris, France, Joseph Bolgone (Kelvin Harrison Jr.) is a master artist with a violin, building quite a name for himself with performances that mesmerize audiences, including seeking the attention of France’s royalty, Marie Antionette (Lucy Boynton), Become so enamored with the musician’s talents, the Queen of France bestows upon Joseph the title of “Chevalier” status (Chevalier de Saint-Georges), with the biracial man becoming a trusted companion to the Antoinette’s court. Looking to further develop his fame and musical bravado, Joseph sets his sights to become the director of the Paris Opera, seeking the Queen’s favor for approval of such an appointment, with Marie electing for a competition with rival composer Christoph Gluck (Henry Lloyd-Hughes), with the men working on musical opera compositions for the position of the head of the opera organization. Such a task invigorates Joseph, enticing him to set out and build a team of professionals capable of bringing his visionary opera piece to life, including the sudden recruitment of Marie-Josephine (Samara Weaving), a young and prolithic singer as well as the wife of the Marquis de Montalembert (Marton Csokas), who sees jealousy in Chevalier’s work rather than opportunity.",
    
        title3:"THE HUNGER GAMES: THE BALLAD OF SONGBIRDS & SNAKES OFFICIAL TRAILER",
        img3:"https://i0.wp.com/jasonsmovieblog.com/wp-content/uploads/2023/04/e90cef62-baa2-405c-95c1-c1a3912b8843-the-hunger-games-the-ballad-of-songbirds-snakes-BOSS_UNIT_220920_01273_R.jpg_max_rgb-e1682640611197.webp?resize=860%2C280&ssl=1",
        info3:"Every story has a beginning as Lionsgate releases the official trailer for the upcoming prequel to The Hunger Games titled The Hunger Games: The Ballad of Songbirds & Snakes.",
        cpara1:"Every story has a beginning as Lionsgate releases the official trailer for the upcoming prequel to The Hunger Games titled The Hunger Games: The Ballad of Songbirds & Snakes.",
        cpara2:"The Hunger Games: The Ballad of Songbirds & Snakes follows a young Coriolanus (Tom Blyth) who is the last hope for his failing lineage, the once-proud Snow family that has fallen from grace in a post-war Capitol. With his livelihood threatened, Snow is reluctantly assigned to mentor Lucy Gray Baird (Rachel Zegler), a tribute from the impoverished District 12. But after Lucy Gray’s charm captivates the audience of Panem, Snow sees an opportunity to shift their fates. With everything he has worked for hanging in the balance, Snow unites with Lucy Gray to turn the odds in their favor. Battling his instincts for both good and evil, Snow sets out on a race against time to survive and reveal if he will ultimately become a songbird or a snake.",
        cpara3:"Oh wow…. wow! I’m quite impressed with this trailer. I was hoping one would eventually materialize sometime soon and it appears it has. The new trailer showcases plenty of new footage (or rather the first footage shown) definitely looks interesting, with the narrative focusing on a younger President Snow character and how he changes the “Hunger Games” competition to be more of a spectacle rather than a blood sport. Plus, I do like the additional cast, including Viola Davis, Peter Dinklage, and Jason Schwartzman. Overall, I’m very interested to see this prequel endeavor. Heck, I might actually take the time to read the book over the summer before the movie comes out.",

        title4:"WISH OFFICIAL TEASER TRAILER",
        img4:"https://i0.wp.com/jasonsmovieblog.com/wp-content/uploads/2023/04/FcQWDQOaAAEkDht-e1682644706519.jpeg?resize=860%2C280&ssl=1",
        info4:"What is your one wish to make as Walt Disney Studios releases the official teaser trailer for their upcoming animated film Wish. View trailer below.",
        dpara1:"What is your one wish to make as Walt Disney Studios releases the official teaser trailer for their upcoming animated film Wish.",
        dpara2:"The movie focuses on a 17-year-old girl named Asha (DeBose) who makes a passionate plea to the stars in a moment of need when she senses a darkness in the Kingdom of Rosas that no one else does.",
        dpara3:"Wow….I was curious about this film for quite sometime. It’s definitely a Disney movie, with the classic signature style of music and animation nuances that the studio is known for. Details on the plot is vague (for now at least), but the animation style looks quite unique and I do like DeBose in the lead role. You can easily tell that Disney is trying to pull all the stops on this particular movie, especially since it brings up all those past and beloved Disney animated films in the preview. It definitely has the making of it, so let’s hope that it does. In the end, I’m quite excited to see Wish and I’m definitely curious to see how both critics and moviegoers will look upon this movie.",

        title5:"TRANSFORMERS: RISE OF THE BEASTS OFFICIAL TRAILER",
        img5:"https://i0.wp.com/jasonsmovieblog.com/wp-content/uploads/2023/04/ROTB-Promotional-poster-00-e1682635114753.jpg?zoom=2&resize=860%2C280&ssl=1",
        info5:"Get ready to “Unite or Fall” as Paramount Pictures releases the official trailer for the upcoming action-adventure blockbuster sequel Transformers: Rise of the Beasts. View trailer below.",
        epara1:"Get ready to “Unite or Fall” as Paramount Pictures releases the official trailer for the upcoming action-adventure blockbuster sequel Transformers: Rise of the Beasts.",
        epara2:"Returning to the action and spectacle that have captured moviegoers around the world, Transformers: Rise of the Beasts will take audiences on a ‘90s globetrotting adventure with the Autobots and introduce a whole new faction of Transformers – the Maximals – to join them as allies in the existing battle for earth.",
        epara3:"A new trailer for this movie is here and it’s kind of interesting. For starters, the previews addresses the timeline placement of Rise of the Beasts, with the movie taking place in 1994, which means this is continuation of Bumblebee film timeline and not continuing Transformers: Last Knight. From the trailer, the movie looks pretty good and introduces a lot of new characters, which has me a little bit worried as the feature looks more and more to like the past Transformers flicks that are more bloated and excessive in CGI and goofy characters. Overall, I still have both my interest (as well as my leeriness) about this particular Transformers movie. Hopefully, the film is pretty and succeeds my expectations. Only time will tell…..",

        title6:"A HAUNTING IN VENICE OFFICIAL TEASER TRAILER",
        img6:"https://i0.wp.com/jasonsmovieblog.com/wp-content/uploads/2023/04/screenshot_2023-04-26_at_20_a61bdffb.jpg?resize=860%2C280&ssl=1",
        info6:"Death is just the beginning as 20th Century Studios releases the official teaser trailer for the upcoming murder mystery thriller A Haunting in Venice. View trailer below.",
        fpara1:"Death is just the beginning as 20th Century Studios releases the official teaser trailer for the upcoming murder mystery thriller A Haunting in Venice.",
        fpara2:"Set in eerie, post-World War II Venice on All Hallows’ Eve, “A Haunting in Venice” is a terrifying mystery featuring the return of the celebrated sleuth, Hercule Poirot. Now retired and living in self-imposed exile in the world’s most glamorous city, Poirot reluctantly attends a séance at a decaying, haunted palazzo. When one of the guests is murdered, the detective is thrust into a sinister world of shadows and secrets.",
        fpara3:"Oh wow…. totally forgot that this movie was coming out. So, seeing this new trailer was quite a welcomed sight. Despite some mixed reviews about the previous two films, I personally love Branagh’s film adaptation interoperations of Agatha Christie’s Hercule Poirot and the mysteries that he solves. This new preview for the next exciting adventure that Poirot finds himself is quite different from the previous installments. Of course, trailers could be deceiving from the actual film, but the preview definitely has that horror vibe throughout. Plus, like before, the cast assembled for the picture is quite solid and gets me excited. Overall, I’m definitely quite intrigued to see this particular movie.",

        title7:"SPIDER MAN  2",
        img7:"https://external-preview.redd.it/marvels-spider-man-2-prequel-comic-announced-for-free-comic-v0-5ccD8pgNeY8GxUMpybyeIDToOLIZ5m8klESCOGkyuII.jpg?width=640&crop=smart&auto=webp&s=32290fa7a8680a53887fd06bb2b69e291cf653c2",
        info7:"The end of era and beginning of something new as Warner Bros. Studio releases the new offical trailer for the upcoming superhero film Spiderman 2. View trailer below.",
        gpara1:"Taking place sometime after the events of The Amazing Spider-Man, life as superhero is become a routine to Peter Parker (Andrew Garfield) He’s taking care of bad guys and protecting the city, while living a normal life; trying to make sure he stays one step ahead of his aunt (Sally Fields) and struggling with a promise he made to his relationship at a distance with Gwen Stacy (Emma Stone), who is also struggling with her relationship with dating Peter and his alter ego of Spider-Man. At the same time, Max Dillion (Jamie Foxx), a socially challenged and undervalued electrical engineer at Oscorp, accidentally falls into a tank of electrified eels and is reborn as Electro, a super-powered man with the power to harness and conduct electricity.",
        gpara2:" Relationship-wise, it’s a Peter Parker-Mary Jane versus Peter Parker-Gwen Stacey, so comparing it will be like comparing apples and oranges. Although I’ve got to admit the effects of the Amazing Spider-Man trilogy is much better (10 years does a lot for the CGI).",
        gpara3:"Though Peter Parker is torn between superheroics and love, and Doctor Octopus is split between good and evil (as he and his tentacles battle for control of his mind) Sam Raimi and his team don't fuss. They provide everything with utter confidence that will find it all thrilling. How many superhero films give us such a peak into the warm marriage of a villain? How many climaxes are the villain saving the day?",
                                        // Top Post 
        title8:"SHAZAM! FURY OF THE GODS (2023) REVIEW",
        img8:"https://i0.wp.com/jasonsmovieblog.com/wp-content/uploads/2023/03/gb_uk_shzam2_wb_com_uber_main_4320x1080_intl-e1682040203920.jpg?zoom=2&resize=860%2C280&ssl=1",
        info8:"A BIGGER ADVENTURE, AN AVEARGE SUPERHERO TALE   In 2019, the DCEU was continuing to struggle to find its footing amongst the superhero genre, especially with prior mixed receptions of feature films, including Batman v Superman: Dawn of Justice, Suicide Squad, and Justice League.",
        hpara1:"In 2019, the DCEU was continuing to struggle to find its footing amongst the superhero genre, especially with prior mixed receptions of feature films, including Batman v Superman: Dawn of Justice, Suicide Squad, and Justice League. That being said, this shared cinematic universe of DC Comic’s heroes and villains has shone effectively with other releases such as Wonder Woman and Aquaman; proving that the franchise still has life within its comic book source material (just needed to be tweaked more). This proved to be quite the foreground for the likes of other superheroes from the DC background to make their big-screen debut, including the likes of Shazam in the 2019 movie Shazam!, the seventh installment in the DCEU. Directed by David F.",
        hpara2:"Sandberg, the film, which starred Zachary Levi, Asher Angel, Jack Dylan Grazer, and Mark Strong, follows teenager Billy Batson, who is chosen by an ancient wizard to his new champion by saying the name “Shazam”, allowing him to transform into adult superhero with incredible various superpowers, while also dealing with parental past struggles as well as stopping the evil threats from Dr. Thaddeus Sivana and his Seven Deadly Sins monsters. Shazam! went on to become a critical success amongst moviegoers, who praised the feature for Sandberg’s direction and the performances from Levi, Angel, and Grazer, as well as lighter tone / sense of fun.",
        hpara3:"The daughters of Atlas have returned and seek dominion over the mortal world as Billy Batson and his adopted family must thwart their plans and save the day in the movie Shazam! Fury of the Gods. Director David F. Sandberg’s latest film continues what he was able to establish in the 2019 film and builds upon it, with a follow-up sequel that’s just as fun and easily accessible as it was last go around. While the movie does struggle to find a proper balance of action and drama as well several flat characters, the feature still manages to make an entertaining impression with enough silly moments, visual blockbuster spectacle, a great score, and a mostly overall solid cast. Personally, I thought that this movie was somewhere between okay and good. Basically, it sort of met my expectations (I didn’t have a whole lot for this sequel), but didn’t exactly “blown me away”.",

        title9:"PETER PAN & WENDY (2023) REVIEW",
        img9:"https://i0.wp.com/jasonsmovieblog.com/wp-content/uploads/2023/05/2023-peter-pan-and-wendy-ug-e1684542452792.jpg?zoom=2&resize=880%2C290&ssl=1",
        ipara1:"Peter Pan. Captain Hook. Tinkerbell. The Lost Boys. Neverland. All of these are iconic staples in the beloved children’s book Peter Pan. Written by Scottish writer J.M. Barrie, Peter Pan or known as “The Boy Who Wouldn’t Grow Up” was originally written as a play in 1904 and then became a novel some years later (with Barrie revising the story several times before its publication date). Though it’s been over a century, Barrie’s Peter Pan is still being retold to kids everywhere and has become a classic tale in children literature. Along with the original story, Peter Pan has also transcended into different media facets, adapting the celebrated adventure to be told in cartoons, TV programs, feature films, and other written works by other authors. ",
        ipara2:"Thus, it would seem that almost every corner of Peter Pan’s adventures in Neverland has already been told and examined, including prequels and sequels endeavors to Barrie’s original narrative. Now, in keeping with its on-going continuation of reinventing their iconic animated classic into live-action features, Walt Disney Studios and director David Lowery present the updated look from their 1953 beloved animated film with the release Peter Pan & Wendy. Does this new iteration of iconic character stay true to the cherished story or is it a visual flop and a far cry from Barrie’s description?",
        ipara3:"Caught in between childhood and adulthood, Wendy Darling, along with her two brothers, are swept up by the magical Peter Pan and whisked away to Neverland to discover more about herself, while also dealing with the nefarious Captain Hook in the movie Peter Pan & Wendy. Director David Lowery’s latest film takes the iconic tale of J.M. Barrie’s Peter Pan character (as well as Disney’s 1953’s animated classic) into a live-action treatment that captures the traditional manner of the narrative, while also interject a few new ideas and more grounded tale of realism. While the director’s signature style (directing and visual presence) is felt throughout and a solid performance from Jude Law, the rest of the movie feels quite underwhelming and lacks that magical spark of its source material, especially when considering a more realistic depiction of certain aspects, a rushed narrative progression, several odd creative decisions, and a few unmemorable characters / performances. Personally, I thought that the movie was just okay, but more on the disappointing side of things.",

        title10:"THE CREATOR OFFICIAL TEASER TRAILER",
        img10:"https://i0.wp.com/jasonsmovieblog.com/wp-content/uploads/2023/05/The-Creator.webp?resize=880%2C290&ssl=1",
        jpara1:"A fight for existence begins as 20th Century Fox releases the official teaser trailer for the upcoming sci-fi adventure film titled The Creator. View trailer below.",
        jpara2:"Amid a future war between the human race and the forces of artificial intelligence, Joshua, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.",
        jpara3:"Very interesting. I’m quite intrigued by this movie. Definitely something I wasn’t expecting, especially since this was the first time I heard about this upcoming film, but I’m glad that I did. I always love a good sci-fi movie and The Creator seems to be right up my alley of Hollywood blockbuster visual flair within the story of high-brow storytelling concepts. The trailer itself looks quite intriguing, which has me quite interested in seeing the movie. How will this movie be received by critics and moviegoers still remains to be seeing. For now, however, I’m quite optimistic for this project and can’t wait to see The Creator this Fall.",

        title11:"GUARDIANS OF THE GALAXY VOLUME 3 (2023) REVIEW",
        img11:"https://i0.wp.com/jasonsmovieblog.com/wp-content/uploads/2023/05/1291881.jpg?zoom=2&resize=880%2C290&ssl=1",
        kpara1:"Back in 2014, Marvel Studios released Guardians of the Galaxy, their 10th film in their shared cinematic universe of superhero (aka the MCU) and took a departure from the well-known and established rosters of characters from the previous entries and brought a sci-fi cosmic aspect through its usage of storytelling, locations, and characters. It was definitely different from past iteration in the MCU, especially with a group of main characters who didn’t comic book pedigree nor the screen-time exposure to the masses against the likes of Iron Man, Captain America, Thor, and the Hulk. However, the success of 2014’s Guardians of the Galaxy was a triumphant victory for the MCU, with many praising the superhero feature for its screenplay, direction, acting, humor, soundtrack, visual effects, and action sequences. The movie also grossed roughly over $770 million globally and became the third highest grossing film of 2014. ",
        kpara2:"Given those notion and how much the fans loved the Guardians team, a sequel was shortly greenlit thereafter and in 2017 the next chapter was released in Guardians of the Galaxy Vol 2, with director James Gunn returning to helm the project as well as principal cast. Like its predecessor, Vol. 2 received the same type of praise (humor, direction, acting, action, soundtrack, etc.) and grossed over $869 million at the box office. While a third Guardians movie was immediately greenlit following Vol. 2’s release, the Guardians of the Galaxy team appeared in other MCU superhero films, including blockbuster team features Avengers: Infinity War in 2018 and Avengers: Endgame in 2019 as well as Thor: Love and Thunder in 2022. ",
        kpara3:"Continuing to build a base of operations on Knowhere, the Guardians of the Galaxy team, including Peter Quill (Chris Pratt), Drax the Destroyer (Dave Bautista), Nebula (Karen Gillian), Mantis (Pom Klemntieff), Groot (Vin Diesel), and Rocket Racoon (Bradley Cooper) are ready to settle down with their lives and get away from daily heroics of daring-do. Unexpectedly arriving to the colony is Adam Warlock (Will Poulter), son of Ayesha (Elizabeth Debicki), who’s been tasked to retrieve Rocket, managing to nearly kill the racoon during his task. Realizing they need special info to help save Rocket’s life, the rest of the Guardians make their way to a corporate space station to collect their fellow team member’s history.",
        
    },

    {
        id:4,
        cat:"Fitness-Images",

        title1:"Preventing Injuries in Youth",
        img1:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRURT9zI9wbOuRK1FP31y1EdjdqCaiNT0sWOw&usqp=CAU",
        info1:"Participating in  at a young age is a familiar path for many kids growing up in Australia. Yet as...",
        apara1:"Participating in  at a young age is a familiar path for many kids growing up in Australia. Yet as our kids move into their teenage years, there is a stark drop off in the progression into sub-elite or elite teams. One of the main reasons for this dropout rate is injury. So, what are the most common injuries we see in young ers, what increases the risk of injuries and what can we do to prevent them?",
        apara2:"The most common  injuries we generally see are hamstring strains, followed by rotator cuff injuries, medial meniscus tears, ankle sprains and more severely lumbar stress fractures. While the incidence of injury in youth  is relatively similar, the prevalence of injuries has increased due to recent changes in game format. These changes include increased volume of  played and reduced rest between games. We see most -specific injuries in bowlers (45%), followed by fielders (30%) and wicket keepers (25%).",
        apara3:"There are numerous factors which may lead to the increase of  injury in Australia. Adolescents are more prone to injury for several reasons. These include asymmetries in muscular strength and flexibility, uncoordinated movement patterns due to a lack of muscle control and sudden workload changes. In order to reduce the risk of injury from any of these factors, the initial step requires adequate programming to modify the er’s conditioning level.",

        title2:"How exercise can help those with bipolar disorder",
        img2:"https://exerciseright.com.au/wp-content/uploads/2022/08/bipolar.jpg",
        info2:"Bipolar disorder is a serious, lifelong mental health condition that affects about one in 50 Australians. Women are more likely...",
        bpara1:"Bipolar disorder is a serious, lifelong mental health condition that affects about one in 50 Australians. Women are more likely to experience the condition than men. Symptoms usually start during the teenage or young adult years.",
        bpara2:"People with bipolar disorder experience changing moods that range from extreme highs to extreme lows. The highs usually involve feelings of euphoria, high energy, excessive activity, less need for sleep, and grand ideas. The lows are characterised by depressive symptoms like poor concentration, low energy and motivation, feelings of sadness and hopelessness, and sleep and appetite changes.",
        bpara3:"People with bipolar disorder have a higher risk of developing a range of health problems, including obesity, diabetes and cardiovascular disease. Additionally, some medications used to treat bipolar disorder can lead to weight gain, adding to the risk of health problems.",

        title3:"Snowboarding: How to get your body ready to shred",
        img3:"https://exerciseright.com.au/wp-content/uploads/2022/08/snowboarding.jpg",
        info3:"Snowboarding is a winter alpine sport that can be done either recreationally or competitively. It involves descending down a mountain...",
        cpara1:"Snowboarding is a winter alpine sport that can be done either recreationally or competitively. It involves descending down a mountain covered in snow, with a board attached to a riders feet. It’s considered to be an “extreme sport” as it elicits a thrill response when part-taking. For anyone who has given it a go, you’ll also know it’s a full-body workout that demands a lot of your muscles!",
        cpara2:"You wouldn’t typically associate Australia with snow sports, however with the recent success of Scotty James and Torah Bright in the snowboarding half pipe, the popularity of the sport has risen in the past decade. Whilst Australia does not have the typical snowfall compared to Europe and Northern America, it is fair to say we punch above our weight category with our successful riders.",
        cpara3:"Snowboarding is considered an ‘extreme sport’ because it’s characterised by high speeds and high risks. It’s a sport that involves a great deal of technical ability, therefore risk of injury is greater in those who are beginning the sport or have less than 1 years’ experience. The greatest management for risk mitigation is to have a lesson to begin with.",

        title4:"Exercise and Bardet-Biedl Syndrome",
        img4:"https://exerciseright.com.au/wp-content/uploads/2022/05/image-from-rawpixel-id-71068-jpeg-compressed.jpg",
        info4:"Bardet-Biedl syndrome (BBS) is a rare genetic condition that affects several body systems, including the kidneys, eyes, and genitalia. People...",
        dpara1:"Bardet-Biedl syndrome (BBS) is a rare genetic condition that affects several body systems, including the kidneys, eyes, and genitalia. People with BBS often have an intellectual disability and may be born with extra fingers or toes. They are also prone to developing abdominal obesity – a condition where fat is deposited mostly around the abdomen (rather than on the arms or legs). People born with BBS are usually a normal weight at birth, but rapidly gain weight in infancy.",
        dpara2:"Overweight and obesity, common features of BBS, are linked with a higher risk of developing several health conditions, including heart disease, type 2 diabetes, some cancers, stroke, high blood pressure and joint problems, among others. Abdominal obesity, in particular, is associated with metabolic changes that can increase the risk of cardiovascular disease. It is estimated that up to 45% of people with BBS have type 2 diabetes.",
        dpara3:"Exercise plays a crucial role in maintaining healthy heart and circulatory function. Exercise also supports a healthy metabolism, helping to reduce the risk of developing metabolic disorders such as type 2 diabetes. Because people with BBS are already prone to these problems, exercise is especially important for maintaining health and reducing disease risk.Exercise can also help with the neurodevelopmental difficulties that affect some people with BBS, such as problems with coordination and motor skill development.",


        title5:"Boost your Brain – why movement is medicine for your mind!",
        img5:"https://exerciseright.com.au/wp-content/uploads/2022/05/brain-health.jpg",
        info5:"Our brain is central to everything we think, feel, and do. Most people know that exercise is good for our...",
        epara1:"Our brain is central to everything we think, feel, and do. Most people know that exercise is good for our body, but many are unaware of the powerful impact exercise has on the health of our brain. Exercise can increase blood flow to the brain, make our brain cells more active, strengthen connections between different brain areas and even make areas of the brain bigger, all of which can improve how well it works and protect it from disease.",
        epara2:"Just like our heart and lungs, our brain is an organ and exercise can improve its performance. While our brain is responsible for many things, one set of skills that can be powerfully improved by exercise is our cognition or thinking skills. These are the mental processes our brain performs so we can learn, understand, and interact with the world. This includes things like our ability to focus, remember, plan, and problem-solve.",
        epara3:"Another important thinking skill that can be improved by exercise is our ability to learn and remember. These skills are fundamental for success at work, study, and in everyday life. Exercise is thought to improve our memory through the powerful effect it has on the health of the hippocampus, a small brain area deep within the temporal lobes of the brain. Studies have shown that exercising at higher intensities (exercise that makes you huff and puff) can make the hippocampus bigger, the cells in the hippocampus healthier, and make the connections between the hippocampus and other areas of the brain stronger. Importantly these improvements in the health of the hippocampus have been linked with improvements in our ability to learn and remember.",

        title6:"Exercise services for rural and remote Australians",
        img6:"https://exerciseright.com.au/wp-content/uploads/2022/04/image-from-rawpixel-id-435499-jpeg-compressed.jpg",
        info6:"If you live in rural or remote Australia, we don’t have to tell you about the strains on resources –...",
        fpara1:"We’re exposed to a range of clients with varying pathologies in rural communities. Most conditions we treat are cardiopulmonary, musculoskeletal and metabolic concerns. It is also not uncommon to manage pre- and post-operative cancer, neurological, renal and mental health related conditions.Another common goal we work towards is prolonging independence for older adults and allowing them to stay active in the community.",
        fpara2:"Many individuals in these regions are susceptible to musculoskeletal injuries that significantly impacts their ability to work. The arduous and repetitive nature of work in the outback predisposes one to musculoskeletal complications. We’re able to provide these members with strategies and movements to continue working with reduced pain, improved fitness and provide them with additional resources to address their comorbidities.",
        fpara3:"It’s all about raising awareness of who we are, what we do, and how we can help people living in rural communities. Some individuals may be hesitant to see us professionally due to the word, ‘exercise’ in our name. So, breaking down misconceptions and bringing awareness to the fact that physical activity can come in many forms with something available for everybody is the first step.",

        title7:"Exercise your brain for optimal thinking",
        img7:"https://exerciseright.com.au/wp-content/uploads/2022/01/exercise-brain-health.jpg",
        info7:"Cognition, or thinking skills, are the mental processes our brain performs so we can acquire knowledge, understand and interact with...",
        gpara1:"Cognition, or thinking skills, are the mental processes our brain performs so we can acquire knowledge, understand and interact with the world around us. This includes our ability to focus, remember, plan, and problem-solve. We generally use these skills automatically, and often don’t notice them until they aren’t working as well as we’d like.",
        gpara2:"Physical exercise can enhance our thinking skills through the powerful effects it has on our brains. Science shows that exercise can increase blood flow to the brain, make our brain cells more active, strengthen connections between different brain regions and even make areas of the brain bigger! But not all exercise is created equal.",
        gpara3:"The frontal lobe (the part of the brain sitting just under your forehead), can be thought of as the control centre of our brain. It is responsible for controlling our ability to focus on what we need to do, ignore distractions, change from one task to another, as well as plan and problem solve. Physical exercise affects our frontal lobe and its functions in many ways. Science shows that just 5-20 minutes of moderate intensity exercise (like a brisk walk, slow jog, leisurely cycle or group sport), can have an immediate positive effect on our ability to concentrate.",
                           // Top Post
        title8:" Empowering Those with Chronic Conditions",
        img8:"https://exerciseright.com.au/wp-content/uploads/2022/09/mental-health-ageing.jpg",
        info8:"Living with a chronic condition can be challenging, but it doesn't mean giving up on a healthy and active lifestyle....",
        hpara1:"Living with a chronic condition can be challenging, but it doesn’t mean giving up on a healthy and active lifestyle. In fact, regular exercise can play a vital role in managing symptoms, improving overall well-being, and reducing the burden of various chronic conditions. As we dive into Exercise Right Week, let’s explore why this campaign holds tremendous support and benefits for individuals with chronic conditions.",
        hpara2:"According to the Australian Institute of Health and Welfare (AIHW), coronary heart disease is the leading specific cause of burden. However, it is noteworthy that the burden from coronary heart disease has shown a significant reduction over time, primarily driven by declines in fatal burden. This highlights the potential for positive change and the importance of proactive measures in managing chronic conditions.",
        hpara3:"During Exercise Right Week, we shine a spotlight on chronic conditions, including but not limited to coronary heart disease, dementia, back pain, chronic obstructive pulmonary disease (COPD), and anxiety disorders. It’s a dedicated time to raise awareness, educate, and empower individuals with chronic conditions to embrace the transformative power of exercise.",

        title9:"Speed training for football players",
        img9:"https://exerciseright.com.au/wp-content/uploads/2022/05/shutterstock_335822396-2048x1367.jpg",
        ipara1:"When you’re watching a game of football, it’s usually high-speed movements that drive match determining plays.Fast attacking players terrorise defenders, put points on the scoreboard, and excite crowds. Fast defenders, on the other hand, can more effectively shut down their opposition and recover from errors.Football coaches recognise the value of speed but are often reluctant to, or incorrectly, include speed development in their programs.",
        ipara2:"Speed is regularly a key criterion in talent identification. Fast players are often selected ahead of ‘skilled’ players as it’s a widely held notion that game skills can be taught but speed is something you’re born with.Of course, there is a genetic ceiling on speed as with all physical attributes, but speed should be considered no less coachable than other facets of football. Many football coaches avoid speed training because it’s considered to be too technical, too dangerous, or out of a belief that the game itself is enough for optimal speed development.",
        ipara3:"It’s important not to remove qualities that make a player fast or limit their movement options. If the player’s sprinting technical deficiencies are unlikely to lead to decreased football performance or injury, then avoid overcoaching. Adjustments may sometimes be more for aesthetics than function. Improved on field ‘football performance’ is the goal.",


        title10:"5 tips for managing your health this festive season",
        img10:"https://exerciseright.com.au/wp-content/uploads/2021/12/festive-season.jpg",
        jpara1:"Despite the celebration and festivities, the stress that comes with the season can seem to be somewhat unavoidable. Whilst maintaining healthy habits may seem difficult over this period, it’s important to recognise the value of good nutrition, sleep and physical activity in ensuring you are reinvigorated, refreshed and ready to tackle 2022. Here are some tips for staying healthy over the next few weeks:",
        jpara2:"Walking is a great way to get some extra movement into your life. Research has shown walking is the most common type of exercise adopted when adults are encouraged to do more physical activity into their lives. It’s also the most likely to be sustained in contrast to other exercise programs because it’s often used as an active means of commuting.",
        jpara3:"Your exercise routine will probably look different over this time of year, and that’s okay! Remember, something is better than nothing. Whether it’s a simple walk around the block Christmas morning, a surf or swim at the local ocean pool, it all counts. Physical activity is important not only for your physical fitness, but also your mental health.",

        title11:"ADHD and physical activity",
        img11:"https://exerciseright.com.au/wp-content/uploads/2021/09/man-exercising-outdoors.jpg",
        kpara1:"Inattention – inability to focus on something for a sustained period of time unless urgent and important or of significant interest e.g., often fails to give close attention to details or makes careless mistakes; often does not seem to listen when spoken to directly; often easily distracted; often forgetful in daily activities.Impulsivity-Hyperactivity (Poor Inhibitory Control) – inability to inhibit a thought, action or movement e.g., often talks excessively; often blurts out an answer before a question has been completed; often interrupts or intrudes on others; often feels restless; often fidgets.",
        kpara2:"The precise cause of ADHD is a complex interaction between genetics and environmental factors that is still being studied. However, ADHD has a significant genetic component with the heritability estimated to be approximately 70-80%. For this reason, it is common to see ADHD running in families.Unfortunately, adults with ADHD experience higher rates of a number of conditions including mental illness (i.e., depression, anxiety, bipolar), neurological disorders, respiratory conditions (e.g., asthma), cardiovascular and metabolic health conditions such as type 2 diabetes and hypertension, addiction and substance use disorders, sleep problems such as insomnia, hypermobility, poor coordination, and accidental injury.",
        kpara3:"In children with ADHD, recent reviews have shown that regular exercise can improve attention, impulsivity, executive functions, motor skills, anxiety and mood. We also know from other studies in adults, that exercise and physical activity can play an important part in managing physical and mental health conditions that are common in ADHD.An Accredited Exercise Physiologist can support you in developing a regular exercise routine that will provide a variety of benefits.",

        
    },

    {
        id:5,
        cat:"Food-Images",

        title1:"Salmon Tacos with Mango Corn Salsa",
        img1:"https://pinchofyum.com/wp-content/uploads/Salmon-Tacos-Square.png",
        info1:"Super easy salmon tacos loaded with a mango, sweet corn, and cucumber salsa!...",
        apara1:"A few nights ago, I made them (again), and I set the sheet pan of salmon down on the table and my whole family literally descended upon it and started grabbing at the salmon with their hands and forks as I stood by watching in half shock, half pride. It was a feeding frenzy.",
        apara2:"The salmon itself is completely SOS (taco seasoning and THAT’S IT), which is why I think it makes sense to put all your effort and energy into the salsa. This salsa is also the thing that’s going to keep you sitting at the table long after you’re done eating tacos, just scooping some extra salsa bites all on its own and suddenly thinking of it as more of a salad? It can be a salad, right? I would totally eat this salsa on its own as a salad.",
        apara3:"Each bite is extra crispy and unexpected from the raw sweet corn and cucumber with a little burst of juicy flavor. But it’s also mainstream enough with the mango that my two young kids are usually happy to devour it right along with us.I love a million sauces on my tacos (okay, fine, on every recipe). But with this one, all it needs is a bit of extra lime and honey to finish it off. Simple, minimal effort, max deliciousness.",

        title2:"Chili Garlic Pappardelle with Smashed Broccoli and Soft Eggs",
        img2:"https://pinchofyum.com/wp-content/uploads/Chili-Garlic-Pappardelle-Square.png",
        info2:"Slippery, spicy, bossy noodles with a minimal-ingredient sauce, topped with a pile of roasty smashed broccoli and a perfectly messy soft egg. Yes, please.",
        bpara1:"Oh man, these slippery, spicy noodles are a TREAT. Silky, rich, full of deep flavor and a flash of heat!I would say this recipe belongs less in the “normal family dinner” category and more in the “hangry / hardcore craving / last minute meal” category.",
        bpara2:"The big flavors end up being a bit much for my kids, so I make this for a need-it-right-now hungry mom moment that calls for something ultra-satisfying, silky, and spicy. I often end up eating it right over the stove in a moment of pure and absolute joy.",
        bpara3:"And luckily, the components can work for everybody (buttered noodles is always a kid win, plus eggs and broccoli!), so it can be easily worked into something family-friendly or meal-prep friendly if you batch some extra broccoli and eggs to throw into other meals throughout the week. SOS at its finest.",

        title3:"Steph’s Chickpea Curry with Spinach and Rice",
        img3:"https://pinchofyum.com/wp-content/uploads/Stephs-Chickpea-Curry-Square.png",
        info3:"Amazingly creamy, saucy chickpea curry served over rice with a dollop of chili crisp and a side of cucumber salad. Ready in 20 minutes!",
        cpara1:"How it happened is that I asked my sister Steph what she’s been making for dinner lately, and she said, “I make that salmon recipe but I just use a can of chickpeas instead to keep it easy.” And now, if you ask me what I’m making for dinner lately, I’m going to say the exact same thing because okay wow that is very delicious and it only takes ten minutes.",
        cpara2:"This chickpea curry is, well, it’s everything. It’s cozy, it’s pantry-friendly, and maybe even a little elegant? *hair toss* even though it’s super super easy? It’s comforting without being heavy, nutritious without being boring, and beautiful without being high maintenance.",
        cpara3:"I came into this realization too late to include it in the photos here, but serving this with a little side of pickled cucumber salad (sliced cucumbers, sliced red onion, white vinegar, olive oil, salt, and sugar) is *chef’s kiss* SOS perfection.With or without the cucumber salad, I can definitely say that swooping the wooden spoon leisurely through that luscious sauce, piling the saucy goodness of chickpeas and spinach over steaming rice.",

        title4:"Miso Crunch Salad",
        img4:"https://pinchofyum.com/wp-content/uploads/Miso-Crunch-Salad-Square.png",
        info4:"Shredded cabbage and kale, shrimp, avocado, cilantro and chili-flavored peanuts, and the perfect sweet miso dressing.",
        dpara1:"Cabbage, kale, shrimp, cilantro, peanuts, and creamy sweet miso dressing… I could eat this every day for lunch and be happy with my life. (And by could, I mean I currently am.)",
        dpara2:"We were actually planning to publish this later in the SOS Series, but I could not wait to get this into your hands because I’m so obsessed with it. So here she is, making an early entrance! This salad is so perfect for these early days of spring / summer when it’s starting to warm up and the grass is turning green again and the body is just feeling aggressively ready for salads.  ",
        dpara3:"And this miso dressing can be blitzed up in about two minutes. It is creamy, sweet, springy, delicate, and just very life-giving. Just a little bit of garlic, but not overpowering, and the punch from the lime is the most delicious little jolt of wake-me-up energy that you want in a salad.",

        title5:"Red Chile Tostadas with Eggs",
        img5:"https://pinchofyum.com/wp-content/uploads/Red-Chile-Tostadas-with-Eggs-Square.png",
        info5:"We’re making Red Chile Tostadas with Eggs! We’re talking creamy, crunchy, drippy, and tangy – the absolute perfect flavor combination.",
        epara1:"The combination of flavors and textures is unmatched, plus so many of these things can be made ahead or store-bought (the enchilada sauce, the refried beans, the tostada if you want). It is my perfect food combination: something creamy, something crunchy, something tangy, and something drippy and messy to really make you feel alive.",
        epara2:"I have eaten (slash, continue to eat) these for ANY meal of the day, which is another reason why I love them. They are breakfast, brunch, lunch, and dinner all in one cute, crunchy little package.",
        epara3:"I hope you love these as much as I do – and if you do, these cauliflower tostadas with queso are your next stop!",

        title6:"Cilantro Orange Chicken with Rice and Beans",
        img6:"https://pinchofyum.com/wp-content/uploads/Cilantro-Orange-Chicken-61-Square-1200x1200.jpg",
        info6:"This golden Cilantro Orange Chicken is so flavorful, crisped to golden brown perfection, and just very finger-licking good! Served with rice, beans, and a quick homemade pineapple salsa.",
        fpara1:"JUICINESS alert! This golden Cilantro Orange Chicken is so flavorful, crisped to golden brown perfection, and just very finger-licking good. You’re going to need some napkins.",
        fpara2:"When I’m being normal, I usually serve it with rice, beans, and quick homemade pineapple salsa – which all just works together so well, you know? It has a Cuban feel to it: a mojo-like sauce with rice and beans and some tropical fruit on the plate for good measure. Yum. Yum yum yum.But the beautiful thing is that if you don’t have time or patience for the extras, or you’re your most hungry and desperate self, the chicken can very much stand on its own.",
        fpara3:"It’s rare for me to really love a “plain chicken” recipe, but this chicken is eat-directly-off-the-pan delicious. Just brush that burnished chicken with some extra sauce straight out of the oven, pass me a couple skewers, and I am done. It’s all I need! Just a snack-turned-dinner standing over the stove.",

        title7:"Butter Chicken Meatballs",
        img7:"https://pinchofyum.com/wp-content/uploads/butter-chicken-3-1200x1200.jpg",
        info7:"These butter chicken meatballs are covered in a rich and mildly spiced tomato gravy that is made luxurious with just a little bit of butter and cream. Serious weeknight magic!",
        gpara1:"These butter chicken meatballs are covered in a rich and mildly spiced tomato gravy that is made luxurious with just a little bit of butter and cream. It is a thing of beauty. I look forward to dinner all day long when I know we are having this. And as I’m sure you imagine, the leftovers are even better, so lunch the next day is something to look forward to, too.",
        gpara2:"You can make it on the stovetop or in the Instant Pot, and you can use a regular or immersion blender to get your sauce nice and creamy. I often have a batch of baked chicken meatballs on hand so I like to use those, but this would be delicious and easy with some store-bought meatballs to really lock in the SOS goodness here",
        gpara3:"There are a lot of spices listed, but the beauty is that you probably already have them all and it takes two minutes or less to measure them and get them cooking into something spectacular.",
                           // Top Post
        title8:"Carrot Cake Coffee Cake",
        img8:"https://pinchofyum.com/wp-content/uploads/Carrot-Cake-Coffee-Cake-1-1200x1200.jpg",
        info8:"Carrot Cake Coffee Cake! A super easy batter loaded with shredded carrots, topped with a thick crumbly cinnamony streusel, and finished with a melty sweet honey butter.",
        hpara1:"Carrot Cake Coffee Cake! A super easy batter loaded with shredded carrots, topped with a thick crumbly cinnamony streusel, and finished with a melty sweet honey butter.",
        hpara2:"I know it might be confusing – carrot cake, which is like vegetables meets cake, but also still cake, combined with coffee cake, which is also cake but the kind you can eat for breakfast and it will still be totally appropriate and, obviously, cakey?But no need to be confused.",
        hpara3:"If you like a carrot cake that tastes just slightly cinnamony and teeters perfectly between springy and dense…And you like a coffee cake that is loaded with a mega amount of streusel topping…And you like cakes that look beautiful and taste even more beautiful with a proper shmear of honey butter...HELLO! Meet your one true match. This one is for you.",

        title9:"Yummy Salmon Burgers with Slaw",
        img9:"https://pinchofyum.com/wp-content/uploads/salmon-burgers-on-a-plate-1200x1200.jpg",
        ipara1:"These salmon burgers are THE YUMMIEST! and made with just five ingredients. The best for a quick + easy high protein lunch or dinner.",
        ipara2:"These salmon burgers. They are just so extremely good.We’re talking crispy outsides, flaky insides, and a perfect golden color, not to mention lots of nutrition, THANK YOU SALMON.They are also easy to make and require (usually) minimal, if not zero, grocery shopping, assuming you keep a decently stocked pantry. I love, love, love these crispy pan-fried little guys.",
        ipara3:"And as if the salmon burgers weren’t good enough already to eat on their own (which, um, they are), I need you to make this slaw to serve your salmon burgers in/on/around. It is nothing fancy – just a shredded cabbage, yogurt, herbs, garlic, and vinegar situation, but paired with the salmon burgers? The crispy-salty-tangy combo is an ON-POINT combo.",

        title10:"Sopa Tarasca (Pinto Bean Soup) with Jalapeño Corn Fritters",
        img10:"https://pinchofyum.com/wp-content/uploads/Sopa-Tarasca-1-2-1200x1200.jpg",
        jpara1:"Let’s make Sopa Tarasca! It’s a creamy, silky Mexican-inspired soup made with pinto beans, warm chili spices, and whole tomatoes. And you NEED a big pile of the jalapeño corn fritters on top. Drooling over this one!",
        jpara2:"This soup is a hug in a bowl.It’s got a tomato and pinto bean base, with warm chili spices, a creamy silky thickness – and once you add in that generous pile of crispy, sweet, spicy melt-in-your-mouth corn fritters on top, the whole thing is going to have you coming back for more. And more. And then, okay, more again because this one just keeps getting better. Will you make soup art on top with that Mexican crema, cilantro, and salty cotija cheese? We hope so.",
        jpara3:"Sopa Tarasca (“Tarascan soup”) originated in the Michoacán state of Mexico and was given the name in honor of the indigenous peoples of that area, the Purépechas or Tarascos. It is made with tomatoes, garlic, onion, and our favorite little friend, pinto beans! It is also made with fresh or dried chiles native to that region, which help give it its warm smoky flavor.",


        title11:"Ginger Peanut Chicken with Coconut Rice",
        img11:"https://pinchofyum.com/wp-content/uploads/Ginger-Peanut-Chicken-1-1200x1200.jpg",
        kpara1:"Juicy, quick-marinated, Ginger Peanut Chicken on a bed of THE MOST LUSH coconut jasmine rice, with speckles of crunchy peanuts, bright fresh cilantro, and lime squeezes.",
        kpara2:"We really don’t know what to say about this coconut rice other than we…never stop thinking about it? Like, awkwardly so. Have you tried this other SOS fave with coconut rice? Oof.",
        kpara3:"It’s still an easy Instant Pot button-push away (or rice cooker/stove top if you prefer), so no extra work, but it IS extra luxe. That coconut milk just replaces part of the cooking liquid – yep, it’s that simple – and the result is out of this world. It doesn’t turn out creamy exactly, but it is just sort of…velvety? Is that a thing?",

        
    },
    ])
  return (
  <>
  <Store.Provider value={[data,setdata]}>
    {props.children}
  </Store.Provider>
  </>
  )
}

export default ContextApi